version: "3"
services:
  directus:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8055:8055
    volumes:
      - ./directus/database:/directus/database
      - ./directus/uploads:/directus/uploads
      - ./directus/extensions:/directus/extensions
    depends_on:
      - db
    environment:
      SECRET: "replace-with-secure-random-value"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"
      DB_DATABASE: "directus"
      DB_CLIENT: "mssql"
      DB_HOST: "db"
      DB_PORT: "1433"
      DB_USER: "sa"
      DB_PASSWORD: "ZUNsYG8NL7NWtcDMm8w8"
      WEBSOCKETS_ENABLED: "true"
      EXTENSIONS_AUTO_RELOAD: "true"
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "1000"
  db:
    image: "mcr.microsoft.com/azure-sql-edge"
    ports:
      - "1433:1433"
    expose:
      - 1433
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ZUNsYG8NL7NWtcDMm8w8
      MSSQL_PID: Developer
